### ISSUE TITLE
Questions about SCAFFOLD code

### ISSUE THREAD

**Issue by knight-fzq** [QinbinLi/MOON#10]
Hi, I am very interested in your work. I found some results of SCAFFOLD in your paper, but there is no codes about it. Could i know how you reproduce it with your codes. If convenient, can you release your codes about SCAFFOLD.

**Comment by QinbinLi** [comment]
Hi @knight-fzq ,

Please refer to [this repo](https://github.com/Xtra-Computing/NIID-Bench) for the code of SCAFFOLD.

**Comment by knight-fzq** [comment]
Thank you very much!!!
