### ISSUE TITLE
About the model Resnet50

### ISSUE THREAD

**Issue by Skye601** [QinbinLi/MOON#15]
What's the difference between the "models.resnet50(pretrained=False)" and "ResNet50_cifar10()" in model.py?

**Comment by Skye601** [comment]
Thanks for your reply. when training on tinyimagenet, should `models.resnet50()` or `ResNet50_cifar10() `be used?  If there exists the model head ( two FC layers), it seems like choosing `ResNet50_cifar10()`.

**Comment by QinbinLi** [comment]
Hi @Skye601 ,

I used `ResNet50_cifar10()` in the paper's experiments. You can also try `models.resnet50()` to see which one has a better performance.
