### ISSUE TITLE
About w_i^t in paper.

### ISSUE THREAD

**Issue by dadongsuperdong** [QinbinLi/MOON#16]
I have learned a lot and this is an excellent piece of work！

I have some questions in paper and code:
1. In paper, I donot really understand how to get w_i^t(in Algorithm1 procedure 10 it shows we get w_i^t by w_t,how does this work?)
 
2. in main.py line499,
` local_train_net(nets_this_round, args, net_dataidx_map, train_dl=train_dl, test_dl=test_dl, global_model = global_model, prev_model_pool=old_nets_pool, round=round, device=device),`
I think w_i^t is in `nets_this_round`,and this is initialized from nets(). Is this(w_i^t) donot change with training?

**Comment by QinbinLi** [comment]
Hi @dadongsuperdong ,

1. It's an assignment operator. The received global model is used as the initialized local model for the next round. It is same as [FedAvg](https://arxiv.org/pdf/1602.05629.pdf).

2. w_i^t will be updated to w_i^{t+1} during the local training stage. You may refer to `train_net_fedcon` function (line 246 of main.py).
