### ISSUE TITLE
Why does the program keep showing“Files already downloaded and verified”

### ISSUE THREAD

**Issue by xuan240** [QinbinLi/MOON#17]
![Uploading 微信图片_20220926171046.jpg…]()

**Comment by xuan240** [comment]
![微信图片_20220926171046](https://user-images.githubusercontent.com/80311623/192239061-2d755b02-30c3-46dd-a4f8-f419cb087342.jpg)

**Comment by QinbinLi** [comment]
Hi @xuan240 ,

It's just logging information output by pytorch. The program is successfully running. You should be able to see the log file under "logs/" directory. You can specify the logging directory by parameter `logdir`.

**Comment by xuan240** [comment]
thank you!

**Comment by Xiaodiudiudiu** [comment]
hi! I meet the same problem right now, and I wonder where is the "logs/" dir?

**Comment by QinbinLi** [comment]
Hi @Xiaodiudiudiu ,

By default, it is under "MOON" directory if you did not specify it in the parameters.

**Comment by Xiaodiudiudiu** [comment]
> 

thank you!
