### ISSUE TITLE
Processing of Datasets

### ISSUE THREAD

**Issue by junzhang-zj** [QinbinLi/MOON#19]
Hey, I had a question about the dataset processing, whether the final version of MOON's transformation in the dataloader only applied 'transforms.ToTensor()' and nothing like 'transforms.Normalize()'.
I really need your help so that I can follow my work better.

**Comment by QinbinLi** [comment]
Hi @junzhang-zj ,

For the used transformation during training, you can refer to the get_dataloader function in https://github.com/QinbinLi/MOON/blob/main/utils.py. 'transforms.Normalize()' is included.

**Comment by junzhang-zj** [comment]
Thank you! I confused partition_data with get_dataloader.
