### ISSUE TITLE
Question about FedAvg code

### ISSUE THREAD

**Issue by Grassyue** [QinbinLi/MOON#2]
Thanks for sharing your code, it is an amazing work！
But I have a question on the implementation of FedAvg：
https://github.com/QinbinLi/MOON/blob/dbf6344b15029ebce59e15053772a82fbed61d91/main.py#L587

why here aggregation without a "mean" operation ?

**Comment by qiaojy19** [comment]
> fed_avg_freqs[net_id]

I think `fed_avg_freqs[net_id]` means the weight

**Comment by QinbinLi** [comment]
Hi @Grassyue and @qiaojy19 ,

Yes, `fed_avg_freqs[net_id]` is the weight of each model. The weight is related to the data size of each party. The weights are not equal to 1/n if the data size of each party is different.

**Comment by Grassyue** [comment]
Thank you for your reply! :smiley: @qiaojy19 @QinbinLi
