### ISSUE TITLE
Convergence theory analysis

### ISSUE THREAD

**Issue by li200005** [QinbinLi/MOON#21]
Hello, this article I think is very novel, and the application of comparative learning ideas is simply brilliant. But when I wanted to integrate it into my own work, I encountered the problem of convergence theory analysis. Is there a convergence analysis for MOON?

**Comment by QinbinLi** [comment]
Hi @li200005 ,

Thanks for your interest in our work! Sorry that we do not provide a convergence analysis for MOON. You may refer to the convergence analysis of other federated learning studies (e.g., [1][2]) for help.

[1] Federated optimization in heterogeneous networks
[2] Scaffold: Stochastic controlled averaging for federated learning
