### ISSUE TITLE
For tinyimagenet, the test acc is very low, 0.009

### ISSUE THREAD

**Issue by rambo-coder** [QinbinLi/MOON#3]
I run the model as the same as the author for the tinyimagenet, python main.py --dataset=tinyimagenet --model=resnet50 --alg=moon --lr=0.01 --mu=1  --epochs=10 --comm_round=20 --n_parties=10 --partition=noiid --beta=0.5

**Comment by QinbinLi** [comment]
Hi @rambo-coder ,

I can achieve a normal test acc by running your commands with torch 1.0.0 on a V100 GPU. Can you double-check your dataset (i.e., [tiny-imagenet-200](https://www.kaggle.com/c/tiny-imagenet)) and run again? You can also try the other algorithms such as FedAvg to see whether the acc is normal or not. Btw, there is a typo in your commands, "noiid"->"noniid".

**Comment by rambo-coder** [comment]
Hi @QinbinLi, 

Thank you so much for your reply.  
![image](https://user-images.githubusercontent.com/60006565/125378802-f7c4df80-e3c1-11eb-89aa-2b699e5b53e1.png)
I am wondering whether the dataset from kaggle is the same as the dataset from http://cs231n.stanford.edu/tiny-imagenet-200.zip.  It is not available to download the dataset from kaggle now.

**Comment by QinbinLi** [comment]
Hi @rambo-coder ,

What you used is the correct dataset. Did you preprocess the validation folder to move the images to subfolders by the classes ([here is an example](https://github.com/AI-secure/DBA/blob/master/utils/tinyimagenet_reformat.py))?

**Comment by rambo-coder** [comment]
> Hi @rambo-coder ,
> 
> What you used is the correct dataset. Did you preprocess the validation folder to move the images to subfolders by the classes ([here is an example](https://github.com/AI-secure/DBA/blob/master/utils/tinyimagenet_reformat.py))?

Thanks, @QinbinLi , It works now. That is the reason !
