### ISSUE TITLE
Some questions about the metrics.

### ISSUE THREAD

**Issue by ddghjikle** [QinbinLi/MOON#4]
Hi, thanks very much  for the codes. Recently, I have re-generated the released codes under the default setting. However, I cannot find the metrics presented in your paper. It seems that the released codes can only compute the metrics of the global network or each local network. Therefore, could you please tell us which metric is used in your paper?

**Comment by QinbinLi** [comment]
Hi @ddghjikle ,

We use the top 1 test accuracy of the global network on the global test dataset as the metric in our paper (e.g., line 167 of main.py).

**Comment by ddghjikle** [comment]
Thank you very much.

**Comment by QinbinLi** [comment]
Hi @ddghjikle ,

Sorry that I just referred to the wrong code. It should be line 533 of main.py. Line 167 is the test accuracy of the local model.

**Comment by ddghjikle** [comment]
Oh，thanks again. I believe this is a wonderful work for this field.



发自我的iPhone


------------------ Original ------------------
From: Qinbin Li ***@***.***&gt;
Date: Mon,Aug 9,2021 9:33 PM
To: QinbinLi/MOON ***@***.***&gt;
Cc: ddghjikle ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [QinbinLi/MOON] Some questions about the metrics. (#4)

**Comment by QinbinLi** [comment]
Thanks!
