### ISSUE TITLE
L2 norm code issue

### ISSUE THREAD

**Issue by zhangyuanying421** [QinbinLi/MOON#9]
Hi, I am very interested in your work, is there no code with loss function L2 norm？

**Comment by QinbinLi** [comment]
Hi @zhangyuanying421 ,

If you refer to the L2 norm distance between the local model and global model, you can simply set `alg` to `fedprox`. If you refer to L2 norm distance between the representations by the local model and global model, you can change line 297-311 of main.py to compute the L2 distance between `pro1` and `pro2` as `loss2`.

**Comment by zhangyuanying421** [comment]
Thank you so much! It's a great job of yours.
